spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "GET, POST, PUT, DELETE"
            allowedHeaders: "*"
            exposedHeaders: "Location"

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: ${SERVER_PORT:8080}

logging.level.org.springframework.security: DEBUG