server.port: 8761

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 1
    serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka