server.port: 9082

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    hostname: localhost
  client:
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
spring:
  application:
    name: fraud-detection

management.endpoints.web.exposure.include: "health,metrics,prometheus"

logging.level.com.netflix: ERROR