server.port: 9081

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    hostname: localhost
  client:
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
spring:
  application:
    name: loan-issuance