apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-storage
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/elastic
    type: DirectoryOrCreate
